<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.2</version>
        <relativePath/>
    </parent>

    <groupId>org.pocfreechoice</groupId>
    <artifactId>poc-free-choice</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>22</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
<!-- Dependencies used in Titan -->
        <dependency>
            <groupId>org.ow2.sat4j</groupId>
            <artifactId>org.ow2.sat4j.core</artifactId>
            <version>2.3.6</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.sat4j</groupId>
            <artifactId>org.ow2.sat4j.pb</artifactId>
            <version>2.3.6</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.2.1-jre</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore</artifactId>
            <version>2.42.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.common</artifactId>
            <version>2.45.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore.xmi</artifactId>
            <version>2.39.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>7.0.0</version>
        </dependency>
<!-- Dependencies taken from Titan-->
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>analysis-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>analysis-freechoice</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>solvers-sat</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>model-variability</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>model-petrinet</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>analysis-featureide</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pnpl</groupId>
            <artifactId>model-variability-editor</artifactId>
            <version>1.0.0</version>
        </dependency>




        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.resources</artifactId>
            <version>3.23.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.runtime</artifactId>
            <version>3.34.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.common</artifactId>
            <version>3.20.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.jobs</artifactId>
            <version>3.15.700</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.xtext</groupId>
            <artifactId>org.eclipse.xtext</artifactId>
            <version>2.40.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.xtext</groupId>
            <artifactId>org.eclipse.xtext.xbase.lib</artifactId>
            <version>2.40.0</version>
        </dependency>
        <dependency>
            <groupId>de.ovgu.featureide</groupId>
            <artifactId>featureide-fm-core</artifactId>
            <version>3.11.1</version>
        </dependency>
        <dependency>
            <groupId>de.ovgu.featureide</groupId>
            <artifactId>featureide-core</artifactId>
            <version>3.11.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>pocfreechoice.PocFreeChoiceApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>